// controls/diagrams/third-party/react/github-repo/ej2-react-github-source/src/schedule/src/schedule/headerrows-directive.tsx
import { ComplexBase } from '@syncfusion/ej2-react-base';
import { HeaderRowsModel } from '@syncfusion/ej2-schedule';

export interface HeaderRowsDirTypecast {
    template?: string | Function | any;
}
/**
 * `HeaderRowsDirective` represent a header rows of the react Schedule. 
 * It must be contained in a Schedule component(`SchduleComponent`). 
 * ```ts
 * <ScheduleComponent>
 *  <HeaderRowsDirective>
 *   <HeaderRowDirective option='Week'></HeaderRowDirective>
 *   <HeaderRowDirective option='Date'></HeaderRowDirective>
 *  <HeaderRowsDirective>
 * </ScheduleComponent>
 * ```
 */
export class HeaderRowDirective extends ComplexBase<HeaderRowsModel| HeaderRowsDirTypecast & { children?: React.ReactNode }, HeaderRowsModel| HeaderRowsDirTypecast> {
    public static moduleName: string = 'headerRow';
}

export class HeaderRowsDirective extends ComplexBase<{}, {}> {
    public static propertyName: string = 'headerRows';
    public static moduleName: string = 'headerRows';
}

// controls/documenteditor/third-party/angular/github-repo/ej2-angular-github-source/src/schedule/src/schedule/headerrows.directive.ts
import { Directive, ViewContainerRef, ContentChildren, ContentChild } from '@angular/core';
import { ComplexBase, ArrayBase, setValue } from '@syncfusion/ej2-angular-base';
import { Template } from '@syncfusion/ej2-angular-base';


let input: string[] = ['option', 'template'];
let outputs: string[] = [];
/**
 * `e-header-rows` directive represent a header rows of the Schedule. 
 * It must be contained in a Schedule component(`ejs-schedule`). 
 * ```html
 * <ejs-schedule>
 *   <e-header-rows>
 *    <e-header-row option='Week'></e-header-row>
 *    <e-header-row option='Date'></e-header-row>
 *   </e-header-rows>
 * </ejs-schedule>
 * ```
 */
@Directive({
    selector: 'e-header-rows>e-header-row',
    inputs: input,
    outputs: outputs,
    standalone: true,
    queries: {
        template: new ContentChild('template')
    }
})
export class HeaderRowDirective extends ComplexBase<HeaderRowDirective> {
    public directivePropList: any;
	


    /** 
     * It defines the header row type, which accepts either of the following values. 
     * * `Year`: Denotes the year row in the header bar. 
     * * `Month`: Denotes the month row in the header bar. 
     * * `Week`: Denotes the week row in the header bar. 
     * * `Date`: Denotes the date row in the header bar. 
     * * `Hour`: Denotes the hour row in the header bar.
     * @default null
     */
    public declare option: any;

    constructor(private viewContainerRef:ViewContainerRef) {
        super();
        setValue('currentInstance', this, this.viewContainerRef);
        this.registerEvents(outputs);
        this.directivePropList = input;
    }
}
Template()(HeaderRowDirective.prototype, 'template');

/**
 * HeaderRow Array Directive
 * @private
 */
@Directive({
    selector: 'ejs-schedule>e-header-rows',
    standalone: true,
    queries: {
        children: new ContentChildren(HeaderRowDirective)
    },
})
export class HeaderRowsDirective extends ArrayBase<HeaderRowsDirective> {
    constructor() {
        super('headerrows');
    }
}
