// controls/grids/third-party/angular/github-repo/ej2-angular-github-source/src/inputs/src/uploader/files.directive.ts
import { Directive, ViewContainerRef, ContentChildren } from '@angular/core';
import { ComplexBase, ArrayBase, setValue } from '@syncfusion/ej2-angular-base';



let input: string[] = ['name', 'size', 'type'];
let outputs: string[] = [];
/**
 * 'e-files' directive represent a file of angular uploader 
 * It must be contained in a Uploader component(`ejs-uploader`). 
 * ```html
 * <ejs-uploader id='fileupload' multiple=true> 
 *   <e-files>
 *    <e-file name='Java' size=23000 type='pdf'></e-file>
 *    <e-file name='C++' size=30000 type='.docx'></e-file>
 *   </e-files>
 * </ejs-uploader>
 * ```
 */
@Directive({
    selector: 'e-files>e-uploadedfiles',
    inputs: input,
    outputs: outputs,
    standalone: true,
    queries: {
    }
})
export class UploadedFilesDirective extends ComplexBase<UploadedFilesDirective> {
    public directivePropList: any;
	


    /** 
     * Specifies the type of the file
     * @default ''
     */
    public declare type: any;
    /** 
     * Specifies the name of the file
     * @default ''
     */
    public declare name: any;
    /** 
     * Specifies the size of the file
     * @default null
     */
    public declare size: any;

    constructor(private viewContainerRef:ViewContainerRef) {
        super();
        setValue('currentInstance', this, this.viewContainerRef);
        this.registerEvents(outputs);
        this.directivePropList = input;
    }
}

/**
 * UploadedFiles Array Directive
 * @private
 */
@Directive({
    selector: 'ejs-uploader>e-files',
    standalone: true,
    queries: {
        children: new ContentChildren(UploadedFilesDirective)
    },
})
export class FilesDirective extends ArrayBase<FilesDirective> {
    constructor() {
        super('files');
    }
}

// controls/grids/third-party/react/github-repo/ej2-react-github-source/src/inputs/src/uploader/files-directive.tsx
import { ComplexBase } from '@syncfusion/ej2-react-base';
import { FilesPropModel } from '@syncfusion/ej2-inputs';


/**
 * `FilesDirective` represent a file of the react uploader. 
 * It must be contained in a Uploader component(`UploaderComponent`). 
 * ```tsx
 * <UploaderComponent multiple={true}> 
 *   <FilesDirective>
 *    <FileDirective name='Java' size=23000 type='pdf'><FileDirective>
 *    <FileDirective name='C++' size=30000 type='.docx'><FileDirective>
 *   </FilesDirective>
 * </UploaderComponent>
 * ```
 */
export class UploadedFilesDirective extends ComplexBase<FilesPropModel & { children?: React.ReactNode }, FilesPropModel> {
    public static moduleName: string = 'uploadedFiles';
}

export class FilesDirective extends ComplexBase<{}, {}> {
    public static propertyName: string = 'files';
    public static moduleName: string = 'files';
}
