// controls/richtexteditorui/third-party/react/github-repo/ej2-react-github-source/src/popups/src/dialog/buttons-directive.tsx
import { ComplexBase } from '@syncfusion/ej2-react-base';
import { ButtonPropsModel } from '@syncfusion/ej2-popups';


/**
 * `ButtonDirective` represent a button of the react dialog. 
 * It must be contained in a Dialog component(`DialogComponent`). 
 * ```tsx
 * <DialogComponent showCloseIcon={true}> 
 *   <ButtonsDirective>
 *     <DialogbuttonDirective buttonModal={this.okButton}></DialogbuttonDirective>
 *     <DialogbuttonDirective buttonModal={this.cancelButton}></DialogbuttonDirective>
 *   <ButtonsDirective>
 * </DialogComponent>
 * ```
 */
export class DialogButtonDirective extends ComplexBase<ButtonPropsModel & { children?: React.ReactNode }, ButtonPropsModel> {
    public static moduleName: string = 'dialogButton';
}

export class ButtonsDirective extends ComplexBase<{}, {}> {
    public static propertyName: string = 'buttons';
    public static moduleName: string = 'buttons';
}

// controls/diagrams/third-party/angular/github-repo/ej2-angular-github-source/src/popups/src/dialog/buttons.directive.ts
import { Directive, ViewContainerRef, ContentChildren } from '@angular/core';
import { ComplexBase, ArrayBase, setValue } from '@syncfusion/ej2-angular-base';



let input: string[] = ['buttonModel', 'isFlat', 'type'];
let outputs: string[] = ['click'];
/**
 * 'e-button' directive represent a button of angular dialog 
 * It must be contained in a Dialog component(`ej-dialog`). 
 * ```html
 * <ejs-dialog id='dialog' showCloseIcon=true> 
 *   <e-buttons>
 *    <e-dialogbutton [buttonModal]='okButton'></e-button>
 *    <e-dialogbutton [buttonModal]='cancelButton'></e-button>
 *   </e-buttons>
 * </ejs-dialog>
 * ```
 */
@Directive({
    selector: 'e-buttons>e-dialogbutton',
    inputs: input,
    outputs: outputs,
    standalone: true,
    queries: {
    }
})
export class DialogButtonDirective extends ComplexBase<DialogButtonDirective> {
    public directivePropList: any;
	public declare click: any;


    /** 
     * Specify the type of the button. 
     * Possible values are Button, Submit and Reset.
     * @default 'Button'
     * @asptype string
     * @blazortype string
     */
    public declare type: any;
    /** 
     * Specifies the button component properties to render the dialog buttons.
     */
    public declare buttonModel: any;
    /** 
     * Specifies the flat appearance of the dialog buttons
     * @default true
     */
    public declare isFlat: any;

    constructor(private viewContainerRef:ViewContainerRef) {
        super();
        setValue('currentInstance', this, this.viewContainerRef);
        this.registerEvents(outputs);
        this.directivePropList = input;
    }
}

/**
 * DialogButton Array Directive
 * @private
 */
@Directive({
    selector: 'ejs-dialog>e-buttons',
    standalone: true,
    queries: {
        children: new ContentChildren(DialogButtonDirective)
    },
})
export class ButtonsDirective extends ArrayBase<ButtonsDirective> {
    constructor() {
        super('buttons');
    }
}
